using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CodingBot.ViewModels
{
    public class AutoGeneratedScriptControlViewModel : ViewModelBase
    {
        private string _script = @"searchlog =
    EXTRACT UID : int,
            StartTime : DateTime,
            Country : string,
            Query : string,
            Duration : int,
            Urls : string,
            ClickUrls : string
";
        public string Script
        {
            get
            {
                return _script;
            }
            set
            {
                _script = value;
                NotifyPropertyChanged("Script");
            }
        }

        public void UpdateScript(string script)
        {
            if (string.Compare(this.Script, script, true) != 0)
            {
                this.Script = script;
            }
        }
    }
}
