using CodingBot.Common;
using CodingBot.ToolWindows;
using CodingBot.ViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace CodingBot.Controls
{
    /// <summary>
    /// Interaction logic for ConversationControl.xaml
    /// </summary>
    public partial class ConversationControl : UserControl, INotifyPropertyChanged
    {
        private const double c_maxConversationBoxWidth = 250;
        private List<string> _radioBoxData = new List<string>();
        private List<string> _checkBoxData = new List<string>();
        private List<string> _checkBoxForSingleTableData = new List<string>();
        private List<List<string>> _multiComboBoxData = new List<List<string>>();
        List<TableItem> _multiComboBoxTableItems = new List<TableItem>();
        public ConversationControl()
        {
            InitializeComponent();
            this.DataContext = this;
            this.UserDataViewModel.RegisterButtonClickEvent(onUserDataButtonClick);
            this._inputBox.GotFocus += new RoutedEventHandler(LabelTextBoxGotFocus);
            this._inputBox.AddHandler(Button.MouseLeftButtonUpEvent, new MouseButtonEventHandler(LableTextBoxMouseLeftButtonUp), true);
        }

        void LabelTextBoxGotFocus(Object sender, EventArgs e)
        {
            this._inputBox.Tag = true;
            this._inputBox.SelectAll();
        }

        void LableTextBoxMouseLeftButtonUp(Object sender, MouseButtonEventArgs e)
        {
            bool? tag = this._inputBox.Tag as bool?;
            if (tag != null && tag == true)
            {
                this._inputBox.SelectAll();
            }
            this._inputBox.Tag = false;
        }

        #region Button Click
        private void onUserDataButtonClick(object sender, EventArgs e)
        {
            this._userDataControl.Visibility = Visibility.Collapsed;
            this.InputBoxVisibility = Visibility.Visible;
        }

        private void InputBoxEnter_Click(object sender, RoutedEventArgs e)
        {
            ShowUserMessageInConversation();

            ResponseData responseData = CodingBotClient.Instance.BotServer.GetResponse(this.InputBoxText);
            //ResponseData responseData = GetFakeResponseData();
            if (responseData != null)
            {
                if (!string.IsNullOrEmpty(responseData.SciptContent))
                {
                    this.AutoGeneratedScriptViewModel?.UpdateScript(responseData.SciptContent);
                }

                ShowBotMessageInConversation(responseData.BotMessage);
                HandleTableOperation(responseData);
            }

            // Empty inputBox when message has been sent to conversation
            this.InputBoxText = null;
        }

        private void CheckRadioBox(object sender, RoutedEventArgs args)
        {
            RadioButton radioButton = sender as RadioButton;
            if (radioButton != null && radioButton.IsChecked == true)
            {
                List<string> requestData = new List<string>();
                requestData.Add(radioButton.Content.ToString());
                this._radioBoxData = requestData;
            }
        }

        private void CheckOrUncheckCheckBox(object sender, RoutedEventArgs args)
        {
            CheckBox checkBox = sender as CheckBox;
            if (checkBox != null)
            {
                if (checkBox.IsChecked == true)
                {
                    this._checkBoxData.Add(checkBox.Content.ToString());
                }
                else
                {
                    if (this._checkBoxData.Contains(checkBox.Content.ToString()))
                    {
                        this._checkBoxData.Remove(checkBox.Content.ToString());
                    }
                }
            }
        }

        private void OnSelectRadioBoxClick(object sender, RoutedEventArgs args)
        {
            Button button = sender as Button;
            if (button != null)
            {
                button.IsEnabled = false;
                var stackPanel = button.Parent as StackPanel;
                if (stackPanel != null && stackPanel.Children != null)
                {
                    foreach (var child in stackPanel.Children)
                    {
                        var radioButton = child as RadioButton;
                        if (radioButton != null)
                        {
                            radioButton.IsEnabled = false;
                        }
                    }
                }

                ResponseData responseData = CodingBotClient.Instance.BotServer.GetResponseInteractive(new List<List<string>> { this._radioBoxData});
                if (responseData != null)
                {
                    if (!string.IsNullOrEmpty(responseData.SciptContent))
                    {
                        this.AutoGeneratedScriptViewModel?.UpdateScript(responseData.SciptContent);
                    }

                    ShowBotMessageInConversation(responseData.BotMessage);
                    HandleTableOperation(responseData);
                }
            }
        }

        private void OnSelectCheckBoxClick(object sender, RoutedEventArgs args)
        {
            Button button = sender as Button;
            if (button != null)
            {
                button.IsEnabled = false;
                var stackPanel = button.Parent as StackPanel;
                if (stackPanel != null && stackPanel.Children != null)
                {
                    foreach (var child in stackPanel.Children)
                    {
                        var checkBox = child as CheckBox;
                        if (checkBox != null)
                        {
                            checkBox.IsEnabled = false;
                        }
                    }
                }

                ResponseData responseData = CodingBotClient.Instance.BotServer.GetResponseInteractive(new List<List<string>> { this._checkBoxData });
                if (responseData != null)
                {
                    if (!string.IsNullOrEmpty(responseData.SciptContent))
                    {
                        this.AutoGeneratedScriptViewModel?.UpdateScript(responseData.SciptContent);
                    }

                    ShowBotMessageInConversation(responseData.BotMessage);
                    HandleTableOperation(responseData);
                }
            }
        }

        private void OnAddMoreButtonClick(object sender, RoutedEventArgs args)
        {
            Button button = sender as Button;
            if (button != null)
            {
                var buttonPanel = button.Parent as StackPanel;
                if (buttonPanel != null)
                {
                    var comboBoxPanel = buttonPanel.Parent as StackPanel;
                    if (comboBoxPanel != null && comboBoxPanel.Children != null)
                    {
                        StackPanel keyPairPanel = CreateKeyPairPanel();
                        // Remove buttonPanel first to let buttonPanel at the end
                        comboBoxPanel.Children.Remove(buttonPanel);
                        comboBoxPanel.Children.Add(keyPairPanel);
                        comboBoxPanel.Children.Add(buttonPanel);
                    }
                }

                ScrollToEnd();
            }
        }

        private void OnFinishButtonClick(object sender, RoutedEventArgs args)
        {
            Button finishButton = sender as Button;
            if (finishButton != null)
            {
                var buttonPanel = finishButton.Parent as StackPanel;
                var comboBoxPanel = buttonPanel?.Parent as StackPanel;
                if (comboBoxPanel != null)
                {
                    List<List<string>> multiComboBoxData = new List<List<string>>();
                    foreach (var comboBoxPanelChild in comboBoxPanel.Children)
                    {
                        var stackPanel = comboBoxPanelChild as StackPanel;
                        if (stackPanel != null)
                        {
                            List<string> keyPair = new List<string>();
                            foreach (var child in stackPanel.Children)
                            {
                                var comboBox = child as ComboBox;
                                if (comboBox != null)
                                {
                                    comboBox.IsEnabled = false;
                                    var item = comboBox.SelectedItem as ComboBoxItem;
                                    keyPair.Add(item.Content.ToString());
                                }

                                var button = child as Button;
                                if (button != null)
                                {
                                    button.IsEnabled = false;
                                }
                            }

                            if (keyPair.Any())
                            {
                                multiComboBoxData.Add(keyPair);
                            }
                        }
                    }

                    this._multiComboBoxData = multiComboBoxData;
                }

                ResponseData responseData = CodingBotClient.Instance.BotServer.GetResponseInteractive(this._multiComboBoxData);
                if (responseData != null)
                {
                    if (!string.IsNullOrEmpty(responseData.SciptContent))
                    {
                        this.AutoGeneratedScriptViewModel?.UpdateScript(responseData.SciptContent);
                    }

                    ShowBotMessageInConversation(responseData.BotMessage);
                    HandleTableOperation(responseData);
                }
            }
        }
        #endregion

        #region Show Content in Conversation functions
        public void ShowBotMessageInConversation(string message)
        {
            TextBlock textBlock = new TextBlock();
            textBlock.Text = message;
            textBlock.TextWrapping = TextWrapping.Wrap;
            textBlock.HorizontalAlignment = HorizontalAlignment.Left;
            textBlock.MaxWidth = c_maxConversationBoxWidth;
            textBlock.Margin = new Thickness(5, 5, 0, 0);
            this._conversationDisplayRegion.Children.Add(textBlock);
            ScrollToEnd();
        }

        private void ShowUserMessageInConversation()
        {
            TextBlock textBlock = new TextBlock();
            textBlock.Text = this.InputBoxText;
            textBlock.TextWrapping = TextWrapping.Wrap;
            textBlock.MaxWidth = c_maxConversationBoxWidth;
            textBlock.HorizontalAlignment = HorizontalAlignment.Right;
            textBlock.Margin = new Thickness(0, 5, 5, 0);
            this._conversationDisplayRegion.Children.Add(textBlock);
            ScrollToEnd();
        }

        private void ShowRadioBoxInConversation(List<TableItem> tableItems)
        {
            if (tableItems != null)
            {
                StackPanel radioBoxPanel = new StackPanel();
                radioBoxPanel.Orientation = Orientation.Vertical;
                radioBoxPanel.HorizontalAlignment = HorizontalAlignment.Left;
                radioBoxPanel.Width = c_maxConversationBoxWidth;
                radioBoxPanel.Margin = new Thickness(10, 5, 5, 0);
                foreach (var tableItem in tableItems)
                {
                    RadioButton radiobutton = new RadioButton();
                    radiobutton.Margin = new Thickness(0, 3, 0, 0);
                    radiobutton.Content = tableItem.TableName;
                    radiobutton.Foreground = this.Foreground;
                    radiobutton.Checked += CheckRadioBox;
                    radioBoxPanel.Children.Add(radiobutton);
                }

                Button button = new Button();
                button.Content = "Select";
                button.Margin = new Thickness(0, 10, 0, 0);
                button.HorizontalAlignment = HorizontalAlignment.Left;
                button.Click += new RoutedEventHandler(OnSelectRadioBoxClick);
                radioBoxPanel.Children.Add(button);

                this._conversationDisplayRegion.Children.Add(radioBoxPanel);
                ScrollToEnd();
            }
        }

        private void ShowCheckBoxInConversation(List<TableItem> tableItems)
        {
            if (tableItems != null)
            {
                this._checkBoxData = new List<string>();
                StackPanel checkBoxPanel = new StackPanel();
                checkBoxPanel.Orientation = Orientation.Vertical;
                checkBoxPanel.HorizontalAlignment = HorizontalAlignment.Left;
                checkBoxPanel.Width = c_maxConversationBoxWidth;
                checkBoxPanel.Margin = new Thickness(10, 5, 5, 0);
                foreach (var tableItem in tableItems)
                {
                    CheckBox checkBox = new CheckBox();
                    checkBox.Margin = new Thickness(0, 3, 0, 0);
                    checkBox.Content = tableItem.TableName;
                    checkBox.Foreground = this.Foreground;
                    checkBox.Checked += CheckOrUncheckCheckBox;
                    checkBox.Unchecked += CheckOrUncheckCheckBox;
                    checkBoxPanel.Children.Add(checkBox);
                }

                Button button = new Button();
                button.Content = "Select";
                button.Margin = new Thickness(0, 10, 0, 0);
                button.HorizontalAlignment = HorizontalAlignment.Left;
                button.Click += new RoutedEventHandler(OnSelectCheckBoxClick);
                checkBoxPanel.Children.Add(button);

                this._conversationDisplayRegion.Children.Add(checkBoxPanel);
                ScrollToEnd();
            }
        }

        private void ShowCheckBoxForSingleTableInConversation(List<TableItem> tableItems)
        {
            if (tableItems != null && tableItems.Count == 1)
            {
                this._checkBoxData = new List<string>();
                StackPanel checkBoxPanel = new StackPanel();
                checkBoxPanel.Orientation = Orientation.Vertical;
                checkBoxPanel.HorizontalAlignment = HorizontalAlignment.Left;
                checkBoxPanel.Width = c_maxConversationBoxWidth;
                checkBoxPanel.Margin = new Thickness(10, 5, 5, 0);
                foreach (var rowItem in tableItems[0].TableData)
                {
                    CheckBox checkBox = new CheckBox();
                    checkBox.Margin = new Thickness(0, 3, 0, 0);
                    checkBox.Content = string.Format("{0}({1})", rowItem.ColumnName, rowItem.DataType);
                    checkBox.Foreground = this.Foreground;
                    checkBox.Checked += CheckOrUncheckCheckBox;
                    checkBox.Unchecked += CheckOrUncheckCheckBox;
                    checkBoxPanel.Children.Add(checkBox);
                }

                Button button = new Button();
                button.Content = "Select";
                button.Margin = new Thickness(0, 10, 0, 0);
                button.HorizontalAlignment = HorizontalAlignment.Left;
                button.Click += new RoutedEventHandler(OnSelectCheckBoxClick);
                checkBoxPanel.Children.Add(button);

                this._conversationDisplayRegion.Children.Add(checkBoxPanel);
                ScrollToEnd();
            }
        }

        private StackPanel CreateKeyPairPanel()
        {
            
            StackPanel keyPairPanel = new StackPanel();
            keyPairPanel.Orientation = Orientation.Horizontal;
            keyPairPanel.Margin = new Thickness(0,5,0,5);
            TextBlock textBlock = new TextBlock();
            textBlock.VerticalAlignment = VerticalAlignment.Center;
            textBlock.Text = "Key Pair:";
            keyPairPanel.Children.Add(textBlock);
            foreach (var tableItem in _multiComboBoxTableItems)
            {
                ComboBox comboBox = new ComboBox();
                comboBox.Width = 100;
                comboBox.SelectedIndex = 0;
                comboBox.Margin = new Thickness(10, 0, 0, 0);
                foreach (var rowItem in tableItem.TableData)
                {
                    if (rowItem != null)
                    {
                        ComboBoxItem comboBoxItem = new ComboBoxItem();
                        comboBoxItem.Content = string.Format("{0}({1})", rowItem.ColumnName, rowItem.DataType);
                        comboBox.Items.Add(comboBoxItem);
                    }  
                }

                keyPairPanel.Children.Add(comboBox);
            }

            return keyPairPanel;
        }

        private void ShowMutiComboBoxInConversation(List<TableItem> tableItems)
        {
            if (tableItems != null)
            {
                this._multiComboBoxTableItems = tableItems;
                // Mutiple combobox panel
                StackPanel comboBoxPanel = new StackPanel();
                comboBoxPanel.Orientation = Orientation.Vertical;
                comboBoxPanel.HorizontalAlignment = HorizontalAlignment.Left;
                comboBoxPanel.Width = c_maxConversationBoxWidth;
                comboBoxPanel.Margin = new Thickness(10, 5, 5, 0);

                // Key pair panel
                StackPanel keyPairPanel = CreateKeyPairPanel();

                // Button panel                
                StackPanel buttonPanel = new StackPanel();
                buttonPanel.Orientation = Orientation.Horizontal;
                Button addMoreButton = new Button();
                addMoreButton.Content = "Add Key Pair";
                addMoreButton.Click += new RoutedEventHandler(OnAddMoreButtonClick);
                buttonPanel.Children.Add(addMoreButton);

                Button finishButton = new Button();
                finishButton.Content = "Finish";
                finishButton.Margin = new Thickness(10,0,0,0);
                finishButton.Click += new RoutedEventHandler(OnFinishButtonClick);
                buttonPanel.Children.Add(finishButton);

                comboBoxPanel.Children.Add(keyPairPanel);
                comboBoxPanel.Children.Add(buttonPanel);

                this._conversationDisplayRegion.Children.Add(comboBoxPanel);
                ScrollToEnd();
            }
        }

        private void UpdateDataStatus(List<TableItem> tableItems)
        {
            if (tableItems != null)
            {
                var dataStatusWindow = CodingBotClient.Instance.ShowToolWindow(typeof(DataStatusToolWindow));
                if (dataStatusWindow != null && dataStatusWindow is DataStatusToolWindow)
                {
                    (dataStatusWindow as DataStatusToolWindow).BindTableDataStatus(tableItems);
                }
            }
        }

        private void HandleTableOperation(ResponseData responseData)
        {
            switch (responseData.TableOperation)
            {
                case TableOperationType.None:
                    break;
                case TableOperationType.ShowRadioBox:
                    ShowRadioBoxInConversation(responseData.TableItems);
                    break;
                case TableOperationType.ShowCheckBox:
                    ShowCheckBoxInConversation(responseData.TableItems);
                    break;
                case TableOperationType.ShowMultiComboBox:
                    ShowMutiComboBoxInConversation(responseData.TableItems);
                    break;
                case TableOperationType.UpdateDataStatus:
                    UpdateDataStatus(responseData.AllTableItems);
                    break;
                case TableOperationType.ShowCheckBoxForSingleTable:
                    ShowCheckBoxForSingleTableInConversation(responseData.TableItems);
                    break;
            }
        }
        #endregion

        int cycle = 0;
        private ResponseData GetFakeResponseData()
        {
            ResponseData responseData = new ResponseData();
            responseData.BotMessage = @"Hello, Dear User,Hello, Dear User,Hello,Hello, Dear User,Hello, Dear User, Hello, Dear User, Hello, Dear User,Hello, Dear User";

            if (cycle % 5 == 0)
            {
                responseData.TableOperation = TableOperationType.ShowRadioBox;
            }
            if (cycle % 5 == 1)
            {
                responseData.TableOperation = TableOperationType.ShowCheckBox;
            }
            if (cycle % 5 == 2)
            {
                responseData.TableOperation = TableOperationType.ShowMultiComboBox;
            }
            if (cycle % 5 == 3)
            {
                responseData.TableOperation = TableOperationType.UpdateDataStatus;
            }
            if (cycle % 5 == 4)
            {
                responseData.TableOperation = TableOperationType.ShowCheckBoxForSingleTable;
            }
            cycle++;
   
            int count = 2;
            if (responseData.TableOperation == TableOperationType.UpdateDataStatus)
            {
                count = 4;
            }

            List<TableItem> tableItems = new List<TableItem>();
            for (int j = 0; j < count; j++)
            {
                TableItem tableItem = new TableItem();
                tableItem.TableName = "Table Item" + j;
                for (int i = 0; i < 4; i++)
                {
                    tableItem.TableData.Add(new RowItem("XiangnanLi", "ZhiweiJia"));
                }

                tableItems.Add(tableItem);
            }

            responseData.TableItems = tableItems;

            return responseData;
        }

        private void ScrollToEnd()
        {
            this._converdationScrollViewer.UpdateLayout();
            this._converdationScrollViewer.ScrollToVerticalOffset(_converdationScrollViewer.ScrollableHeight);
        }

        #region Properties
        private UserDataControlViewModel _userDataViewModel = new UserDataControlViewModel();
        public UserDataControlViewModel UserDataViewModel
        {
            get
            {
                return _userDataViewModel;
            }
            set
            {
                _userDataViewModel = value;
                NotifyPropertyChanged("UserDataViewModel");
            }
        }

        private AutoGeneratedScriptControlViewModel _autoGeneratedScriptViewModel;
        public AutoGeneratedScriptControlViewModel AutoGeneratedScriptViewModel
        {
            get
            {
                if (_autoGeneratedScriptViewModel == null)
                {
                    var window = CodingBotClient.Instance.FindToolWindow(typeof(ScriptToolWindow));
                    if (window != null)
                    {
                        var control = window.Content as AutoGeneratedScriptControl;
                        if (control != null)
                        {
                            _autoGeneratedScriptViewModel = control.DataContext as AutoGeneratedScriptControlViewModel;
                        }
                    }
                }

                return _autoGeneratedScriptViewModel;
            }
        }

        private string _inputBoxText = "I want to ...";
        public string InputBoxText
        {
            get
            {
                return _inputBoxText;
            }
            set
            {
                _inputBoxText = value;
                NotifyPropertyChanged("InputBoxText");
            }
        }

        private Visibility _inputBoxVisibility = Visibility.Collapsed;
        public Visibility InputBoxVisibility
        {
            get
            {
                return _inputBoxVisibility;
            }
            set
            {
                _inputBoxVisibility = value;
                NotifyPropertyChanged("InputBoxVisibility");
            }
        }
        #endregion

        #region Notify Prperty Changed
        public event PropertyChangedEventHandler PropertyChanged;
        protected void NotifyPropertyChanged(string propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
        #endregion
    }
}
